
package com.sergio.ws.mockup;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.5-b01 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "MockupWS", targetNamespace = "http://impl.ws.sergio.com/", wsdlLocation = "file:/C:/unisys/repositories/git/Generador-JAX-WS/gestorws/wsgenResults/wsdl/MockupWS.wsdl")
public class MockupWS_Service
    extends Service
{

    private final static URL MOCKUPWS_WSDL_LOCATION;
    private final static WebServiceException MOCKUPWS_EXCEPTION;
    private final static QName MOCKUPWS_QNAME = new QName("http://impl.ws.sergio.com/", "MockupWS");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/unisys/repositories/git/Generador-JAX-WS/gestorws/wsgenResults/wsdl/MockupWS.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MOCKUPWS_WSDL_LOCATION = url;
        MOCKUPWS_EXCEPTION = e;
    }

    public MockupWS_Service() {
        super(__getWsdlLocation(), MOCKUPWS_QNAME);
    }

    public MockupWS_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), MOCKUPWS_QNAME);
    }

    public MockupWS_Service(URL wsdlLocation) {
        super(wsdlLocation, MOCKUPWS_QNAME);
    }

    public MockupWS_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MOCKUPWS_QNAME);
    }

    public MockupWS_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MockupWS_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName);
    }

    /**
     * 
     * @return
     *     returns MockupWS
     */
    @WebEndpoint(name = "MockupWSImplPort")
    public MockupWS getMockupWSImplPort() {
        return super.getPort(new QName("http://impl.ws.sergio.com/", "MockupWSImplPort"), MockupWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MockupWS
     */
    @WebEndpoint(name = "MockupWSImplPort")
    public MockupWS getMockupWSImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://impl.ws.sergio.com/", "MockupWSImplPort"), MockupWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MOCKUPWS_EXCEPTION!= null) {
            throw MOCKUPWS_EXCEPTION;
        }
        return MOCKUPWS_WSDL_LOCATION;
    }

}
