
package com.unisys.voice.palestra.ws.servidor;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.5-b01 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "EjemploWS", targetNamespace = "http://servidor.ws.palestra.voice.unisys.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface EjemploWS {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns float
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "suma", targetNamespace = "http://servidor.ws.palestra.voice.unisys.com/", className = "com.unisys.voice.palestra.ws.servidor.Suma")
    @ResponseWrapper(localName = "sumaResponse", targetNamespace = "http://servidor.ws.palestra.voice.unisys.com/", className = "com.unisys.voice.palestra.ws.servidor.SumaResponse")
    @Action(input = "http://servidor.ws.palestra.voice.unisys.com/EjemploWS/sumaRequest", output = "http://servidor.ws.palestra.voice.unisys.com/EjemploWS/sumaResponse")
    public float suma(
        @WebParam(name = "arg0", targetNamespace = "")
        float arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        float arg1);

}
