
package com.unisys.voice.palestra.ws.servidor;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.5-b01 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "EjemploWSService", targetNamespace = "http://servidor.ws.palestra.voice.unisys.com/", wsdlLocation = "http://localhost:8080/EjemploWS?wsdl")
public class EjemploWSService
    extends Service
{

    private final static URL EJEMPLOWSSERVICE_WSDL_LOCATION;
    private final static WebServiceException EJEMPLOWSSERVICE_EXCEPTION;
    private final static QName EJEMPLOWSSERVICE_QNAME = new QName("http://servidor.ws.palestra.voice.unisys.com/", "EjemploWSService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/EjemploWS?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        EJEMPLOWSSERVICE_WSDL_LOCATION = url;
        EJEMPLOWSSERVICE_EXCEPTION = e;
    }

    public EjemploWSService() {
        super(__getWsdlLocation(), EJEMPLOWSSERVICE_QNAME);
    }

    public EjemploWSService(WebServiceFeature... features) {
        super(__getWsdlLocation(), EJEMPLOWSSERVICE_QNAME);
    }

    public EjemploWSService(URL wsdlLocation) {
        super(wsdlLocation, EJEMPLOWSSERVICE_QNAME);
    }

    public EjemploWSService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, EJEMPLOWSSERVICE_QNAME);
    }

    public EjemploWSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EjemploWSService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName);
    }

    /**
     * 
     * @return
     *     returns EjemploWS
     */
    @WebEndpoint(name = "EjemploWSPort")
    public EjemploWS getEjemploWSPort() {
        return super.getPort(new QName("http://servidor.ws.palestra.voice.unisys.com/", "EjemploWSPort"), EjemploWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EjemploWS
     */
    @WebEndpoint(name = "EjemploWSPort")
    public EjemploWS getEjemploWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://servidor.ws.palestra.voice.unisys.com/", "EjemploWSPort"), EjemploWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (EJEMPLOWSSERVICE_EXCEPTION!= null) {
            throw EJEMPLOWSSERVICE_EXCEPTION;
        }
        return EJEMPLOWSSERVICE_WSDL_LOCATION;
    }

}
